version: "3"

services:
    # nginx:
    #   build:
    #     context: ./nginx
    #   hostname: nginx
    #   container_name: kabgo-nginx-proxy
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - ./nginx:/etc/nginx
    #   depends_on:
    #     - api-auth
    #     - api-driver
    #     - api-customer
    #     - api-admin
    #     - api-call-center
    #     - api-call-center-s2
    #     - api-call-center-s3
    #     - gps-coordinates
    #     - admin
    #     - call-center
    #     - rabbitmq

    gshoe-service:
        build:
            context: .
        container_name: gshoe-service
        hostname: localhost
        networks:
            - proxy
        ports:
            - "6010:5000"
        environment:
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.gshoe-service.rule=Host(`go-shoe.mtech.id.vn`)
            - traefik.http.routers.gshoe-service.entrypoints=websecure
            - traefik.http.routers.gshoe-service.tls=true
            - traefik.http.routers.gshoe-service.tls.certresolver=letsencrypt
        restart: unless-stopped

networks:
    proxy:
        external: true