version: "3"

services:
    # nginx:
    #   build:
    #     context: ./nginx
    #   hostname: nginx
    #   container_name: kabgo-nginx-proxy
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - ./nginx:/etc/nginx
    #   depends_on:
    #     - api-auth
    #     - api-driver
    #     - api-customer
    #     - api-admin
    #     - api-call-center
    #     - api-call-center-s2
    #     - api-call-center-s3
    #     - gps-coordinates
    #     - admin
    #     - call-center
    #     - rabbitmq

    demand-service:
        build:
            context: ../servers/demand
            dockerfile: Dockerfile.production
        image: wgmin/demand-service
        container_name: demand-service
        hostname: localhost
        networks:
            - proxy
        ports:
            - "5010:5000"
            - "50051:50051"
        environment:
            SUPPLY_GRPC_CLIENT_HOST: "supply.go-shoe.mtech.id.vn"
            SUPPLY_GRPC_CLIENT_PORT: "50052"
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.demand-service.rule=Host(`demand.go-shoe.mtech.id.vn`)
            - traefik.http.routers.demand-service.entrypoints=websecure
            - traefik.http.routers.demand-service.tls=true
            - traefik.http.routers.demand-service.tls.certresolver=letsencrypt
        restart: unless-stopped

networks:
    proxy:
        external: true